'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getAllBlogPosts } from './blogData';
export default function BlogPage(){
 const [posts,setPosts]=useState([]); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All');
 useEffect(()=>{setPosts(getAllBlogPosts());},[]);
 const categories=useMemo(()=>['All',...new Set(posts.map(p=>p.category).filter(Boolean))],[posts]);
 const filteredPosts=useMemo(()=>posts.filter(p=>{const cat=category==='All'||p.category===category; const text=`${p.title} ${p.excerpt} ${p.category}`.toLowerCase(); return cat && text.includes(query.toLowerCase());}),[posts,query,category]);
 const featuredPost=filteredPosts.find(p=>p.featured)||filteredPosts[0]; const normalPosts=filteredPosts.filter(p=>p.slug!==featuredPost?.slug);
 return <main><div className="site-bg"/><div className="cursor-glow"/><header className="navbar"><Link href="/" className="brand"><span className="brand-mark">RA</span><span>Ravindu</span></Link><nav><Link href="/">Portfolio</Link><Link href="/blog">Blog</Link><a href="mailto:ravinduashan66@gmail.com">Contact</a></nav></header><section className="section-shell blog-hero reveal-item is-visible"><p className="section-kicker">My Dev Journal</p><h1>Project stories, coding lessons, and real-world software notes.</h1><p>I use this blog to share what I learn while building Laravel, Next.js, React, POS, e-commerce, mobile, and business systems.</p><div className="blog-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search blog posts..."/><div className="blog-category-list">{categories.map(item=><button key={item} type="button" className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</div></div></section>{featuredPost?<section className="section-shell featured-blog-card reveal-item is-visible"><div className="featured-blog-image" style={{backgroundImage:`url(${featuredPost.image})`}}/><div><span className="blog-badge">Featured Article</span><h2>{featuredPost.title}</h2><p>{featuredPost.excerpt}</p><div className="blog-meta"><span>{featuredPost.category}</span><span>{featuredPost.date}</span><span>{featuredPost.readTime}</span></div><Link className="btn primary" href={`/blog/${featuredPost.slug}`}>Read Article</Link></div></section>:null}<section className="section-shell blog-grid-section"><div className="blog-card-grid">{normalPosts.map(post=><article className="blog-card reveal-item is-visible" key={post.slug}><div className="blog-card-image" style={{backgroundImage:`url(${post.image})`}}/><div className="blog-card-body"><div className="blog-meta"><span>{post.category}</span><span>{post.readTime}</span></div><h3>{post.title}</h3><p>{post.excerpt}</p><Link href={`/blog/${post.slug}`}>Read more →</Link></div></article>)}</div>{!filteredPosts.length?<p className="empty-message">No blog posts found.</p>:null}</section></main>;
}
